### ISSUE TITLE
Manifest is missing on vizality

### ISSUE THREAD

**Issue by bakzkndd** [NYRI4/Comfy#11]
![image](https://user-images.githubusercontent.com/50497725/110258134-37596600-7fa1-11eb-92e7-ad075b451503.png)

**Comment by zzerexx** [comment]
Same thing here on Powercord
![image](https://user-images.githubusercontent.com/74355984/111009733-4d707900-8349-11eb-8bd7-9ef7f8cb0f0a.png)
