### ISSUE TITLE
Not sure if this is intentional.

### ISSUE THREAD

**Issue by Godz-hi** [NYRI4/Comfy#13]
![image](https://user-images.githubusercontent.com/53191186/110407526-f9684a80-8051-11eb-904d-c5b4af4c3720.png)
^^^ Spotify is behind my pfp, not sure if this is intentional, but I will say the other slide-out status was 10x better.

Also a for sure bug (Time of song left): 
![image](https://user-images.githubusercontent.com/53191186/110407601-1f8dea80-8052-11eb-9ba9-16120f89a4cc.png)

**Comment by NYRI4** [comment]
Should be fixed.
