### ISSUE TITLE
betterdiscordlibrary source code link 404

### ISSUE THREAD

**Issue by CesiumCs** [NYRI4/Comfy#15]
Didn't want to make an account on betterdiscordlibrary

Clicking the source code link on the [betterdiscordlibrary page](https://betterdiscordlibrary.com/themes/Comfy) 404s

**Comment by Hades785** [comment]
Links to an old path (https://github.com/NYRI4/Comfy/blob/master/comfy.theme.css) instead of the [current path](https://nyri4.github.io/Comfy/betterdiscord/comfy.theme.css) or to the repo itself.

**Comment by NYRI4** [comment]
Fixed
