### ISSUE TITLE
GameActivityToggle plugin not showing up

### ISSUE THREAD

**Issue by marcpinet** [NYRI4/Comfy#16]
Hello, everything is in the tilte. I also add a GIF to illustrate the issue :

![image](https://i.imgur.com/W5yK1oT.gif)

**Comment by NYRI4** [comment]
?

**Comment by marcpinet** [comment]
> ?

I mean, you need to hover the menu and then make appear a broken tooltip with the logo... er i don't think it's on purpose

**Comment by marcpinet** [comment]
i think it should be better to fix the tooltip and also put the button above the mute one

**Comment by NYRI4** [comment]
4Head

**Comment by marcpinet** [comment]
> 4Head just do it

ratio

**Comment by NYRI4** [comment]
There you go

**Comment by NYRI4** [comment]
![image](https://user-images.githubusercontent.com/65369563/111047587-59456380-844d-11eb-9794-ef1c30b10a44.png)
