### ISSUE TITLE
Theme is dead on Powercord.

### ISSUE THREAD

**Issue by Godz-hi** [NYRI4/Comfy#17]
![image](https://user-images.githubusercontent.com/53191186/111043789-81fc3780-8412-11eb-8364-28fa46edd4e8.png)
First: Error in the console was because the server-list link in 'update.scss' didn't have .scss at the end. But after adding it seems as if the theme still isn't working. 

After adding it there are no more errors and the theme is still broken so Idk what's wrong.

The predefined variables in custom.scss seems to be the only thing applying everything else is broken.
![image](https://user-images.githubusercontent.com/53191186/111043813-ace68b80-8412-11eb-828c-5958b7485b47.png)

**Comment by Snapperito** [comment]
https://github.com/NYRI4/Comfy-git-clone

**Comment by Godz-hi** [comment]
> https://github.com/NYRI4/Comfy-git-clone

Files that aren't being applied are in this repo.

**Comment by NYRI4** [comment]
Back to BetterDiscord main file, not doing scss rewrite for now.
