### ISSUE TITLE
account pic

### ISSUE THREAD

**Issue by antarktidi4** [NYRI4/Comfy#20]
i think it works **differently**.

![image](https://user-images.githubusercontent.com/66149987/112960152-ffa19200-90f8-11eb-8764-fcc47f9f2792.png)

**Comment by Pukimaa** [comment]
Redownload the Theme (update). Nyri4 added a new var which u can change the position. Or paste this into your css file (it needs to be in root):
`/* Avatar position */
--avatar-left: 15px;
--avatar-bottom: 135px;`

**Comment by antarktidi4** [comment]
>Redownload the Theme (update).

so... I installed them 2 times, and on 3 time it work correctly.
Thanks. _I don't have idea how that work lol._
