### ISSUE TITLE
The theme is broken

### ISSUE THREAD

**Issue by marcpinet** [NYRI4/Comfy#21]
Since the last update of BDFDB, the theme is broken. Only the colors are working, the other features just went in the void, lol.
![image](https://user-images.githubusercontent.com/52708150/106398294-4c772e00-6412-11eb-9ecb-714f187b23c4.png)
![image](https://i.imgur.com/yxXU2AI.png)
![image](https://user-images.githubusercontent.com/52708150/106398328-7892af00-6412-11eb-8b77-d60bdec80a98.png)
![image](https://user-images.githubusercontent.com/52708150/106398334-83e5da80-6412-11eb-9abf-da70f7f29230.png)
![image](https://user-images.githubusercontent.com/52708150/106398345-9233f680-6412-11eb-97de-093d73894aeb.png)
![image](https://user-images.githubusercontent.com/52708150/106398363-a7a92080-6412-11eb-8492-f07e934f64bb.png)

**Comment by Godz-hi** [comment]
@marcpinet GO ahead and re download the theme. I'm on powercord and re cloning the theme fixed it for me. Heres the link for what you need since you're on better discord: [](https://github.com/NYRI4/Comfy/blob/main/BetterDiscord/comfy.theme.css).

**Comment by NYRI4** [comment]
I changed the name of the repo to Comfy that's why it broke

**Comment by marcpinet** [comment]
> I changed the name of the repo to Comfy that's why it broke

Yes, it works now, thank you for your quick answer, have a nice day!
