### ISSUE TITLE
Unread indicator hides current server indicator

### ISSUE THREAD

**Issue by Alterae** [NYRI4/Comfy#22]
Theme version: 1.0
PowerCord version: 2.0.0 (I think)
Discord version: whatever the current Discord Canary version is

**Expected behavior:**
The server list should show the currently viewed server in a different manner than all other servers, regardless of read state.

**Actual behavior:**
If the currently viewed server has unread messages, the unread indicator displays and the current server indicator does not, making it more challenging to tell at a glance what the currently viewed server is.

**Comment by NYRI4** [comment]
This should be fixed now.
