### ISSUE TITLE
Powercord Theme tag does not apply

### ISSUE THREAD

**Issue by 0J3** [NYRI4/Comfy#23]
This theme is not a [Powercord](https://powercord.dev) theme, despite having the Powercord-theme tag.
![image](https://user-images.githubusercontent.com/67464646/113521456-d7eb7780-9599-11eb-8565-a6e3a39a6ec6.png)

**Comment by Pukimaa** [comment]
It is just but the Source Code is in another Repo. But Comfy is also a Powercordtheme

**Comment by 0J3** [comment]
wouldn't that mean that that tag only applies to said other repo?

**Comment by Pukimaa** [comment]
Well this is the Repo to Comfy itself and also there are instructions for the Powercordtheme

**Comment by 0J3** [comment]
ok fair enough - sorry for wasting your time

**Comment by Pukimaa** [comment]
Its fine
