### ISSUE TITLE
Move Upload Icon

### ISSUE THREAD

**Issue by KennanHunter** [NYRI4/Comfy#25]
![image](https://user-images.githubusercontent.com/64097683/113785518-46991400-9705-11eb-923b-7107af397c37.png)

Hello, i've really been enjoying using Comfy, i was wondering if it would be possible to move the upload icon to the right. I'm not the best with CSS and certainly not for skinning discord, but i think it might be possible with changing around flexbox properties. Screenshot was just done by moving the \<div> tag. My main reason for asking this is to make it align up with sent messages. Thank you.

**Comment by NYRI4** [comment]
There you go
```
.channelTextArea-rNsIhG .buttons-3JBrkn { order: 2;}
.channelTextArea-rNsIhG .attachWrapper-2TRKBi { order: 1;}
.channelTextArea-rNsIhG .attachWrapper-2TRKBi .attachButton-2WznTc { padding-right: 5px;}
```
