### ISSUE TITLE
Voice Chat Glitch

### ISSUE THREAD

**Issue by martincutcher** [NYRI4/Comfy#27]
I've been using Comfy for about a month and recently it's been doing this with the voice chat avatars when the category is collapsed:
![image](https://user-images.githubusercontent.com/82612961/114931656-8302f900-9e04-11eb-9116-6e5965e6dd22.png)

The avatars also push off the channel bar and disappear when there are more than 6 people in the call instead of making a new line like normal Discord does.

**Comment by Pukimaa** [comment]
The same thing happens if you create a private channel

**Comment by Pukimaa** [comment]
like the little avatars to show who has access to the channel

**Comment by NYRI4** [comment]
![image](https://user-images.githubusercontent.com/65369563/114944761-7902e980-9e48-11eb-8359-549b0c6c166b.png)
Looks like I can't reproduce your issue 🤔 Is it some themes/plugins/custom css interfering ?

**Comment by martincutcher** [comment]
Doesn't look like it, I don't have custom css and I turned all my plugins and themes off and still got this:
![image](https://user-images.githubusercontent.com/82612961/114946452-2bbb5380-9e19-11eb-9a52-ab3d64fb1a54.png)
I also checked to see if it was my theme settings and/or that I was using an older version of the theme by downloading it and trying it and I still got the issue on a fresh downloaded version:
![image](https://user-images.githubusercontent.com/82612961/114946759-d03d9580-9e19-11eb-97a4-70d2e6c4b789.png)

**Comment by NYRI4** [comment]
I ended by removing all masks in Discord and from what I experienced, there's no issues for now so this should be fixed ig

**Comment by martincutcher** [comment]
Yep, looks like it's fixed! Thank you!
![image](https://user-images.githubusercontent.com/82612961/115122838-1a448980-9f88-11eb-929a-53009a6f4abe.png)
