### ISSUE TITLE
Add role popout shows up behind the user popout

### ISSUE THREAD

**Issue by piotr25691** [NYRI4/Comfy#28]
I have noticed that when you click on the plus button to show the add role popout, it will show up behind the user popout making it impossible to add roles.
![image](https://user-images.githubusercontent.com/71488561/115202229-7c230180-a0f6-11eb-84e5-4baa6e296a81.png)
![image](https://user-images.githubusercontent.com/71488561/115202330-98bf3980-a0f6-11eb-9400-924365385d72.png)

**Comment by dav1312** [comment]
I don't have that issue
