### ISSUE TITLE
Discord Status problem

### ISSUE THREAD

**Issue by ArcadeOfficial** [NYRI4/Comfy#3]
![image](https://user-images.githubusercontent.com/79416774/108633673-badd6800-7475-11eb-84b4-3d671804a84a.png)
![image](https://user-images.githubusercontent.com/79416774/108633688-cc267480-7475-11eb-9435-dafcfbc31347.png)
I tried to switch status on Discord but it comes up like this, In the first image I had the Game Activity Toggle plugin on, I thought that was the problem, but when I turned that plugin off, it still came up like this (second image).

**Comment by NYRI4** [comment]
Problem solved, thx to Rud
