### ISSUE TITLE
Mention Channel Glitch

### ISSUE THREAD

**Issue by arsyadbruh** [NYRI4/Comfy#33]
I have a little problem when mention channel the **#** over the text, like this :
![image](https://user-images.githubusercontent.com/71438511/131201539-ad0cedeb-d376-4c9a-9a56-b760f03ddd71.png)

idk it just me or not, but it's a bit annoying

**Comment by NYRI4** [comment]
Its an issue with Revert Rebrand, Ducko is aware of it and will fix it when he's free

**Comment by CanadaHonk** [comment]
Refresh, might be fixed.

**Comment by arsyadbruh** [comment]
thanks, problem fixed
