### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by cckats** [NYRI4/Comfy#34]
The unread message animation is causing high cpu usage on old systems (my old i5 from 1% to 16%)

**Comment by NYRI4** [comment]
#32

**Comment by cckats** [comment]
maybe make it a choice in the edit form?

**Comment by NYRI4** [comment]
Well I don't really if that's the only thing causing high CPU usage or something else but if tell me that it's fine now, I will add it to the variables

**Comment by cckats** [comment]
The code from the other post doesn't seem to be working as custom css. 
But i have already removed it with this custom css:
```
:root .unread-2lAfLh {
  animation: none !important;
}
```
and in standby with many unread messages the usage is again <1%

**Comment by NYRI4** [comment]
The code from the other was designed for Powercord, I thought you were a Powercord user since you're caring about your CPU usage. I'll implement that variable then if it's fixing this issue, thanks for telling me

**Comment by cckats** [comment]
Oh i'm new to the modded discord thing so i haven't heard of powercord. Anyway thanks for implementing a more official fix
