### ISSUE TITLE
Add support for other app

### ISSUE THREAD

**Issue by SquitchYT** [NYRI4/Comfy#40]
Hello, I like very much this theme and I have done one for a Terminal Emulator. If you are interested to add this to your repository, I can give you more details.

**Comment by NYRI4** [comment]
If you want you can post your theme [right here](https://discord.com/channels/811203761619337259/847428145258954769)

**Comment by SquitchYT** [comment]
Hello, the discord invitation link is unavailable...

**Comment by NYRI4** [comment]
https://discord.com/invite/rtBQX5D3bD

**Comment by SquitchYT** [comment]
Okay, thx. Bye
