### ISSUE TITLE
no scrollbar & online indicator bug

### ISSUE THREAD

**Issue by Slluxx** [NYRI4/Comfy#41]
Looks like this theme hides the scrollbar. Id like to see that back to be able to scroll easily. Using arrow keys is not a permanent solution.

Sometimes, the status indicator on people in the right sidebar is a rectangle instead of a square. It seems to happen randomly but is annoying nontheless.

otherwise a great theme

**Comment by NYRI4** [comment]
You can customize Comfy by going into your theme folder and opening `comfy.theme.css` if you're on BetterDiscord, here you'll be able to get the scrollbars back. If the setting isn't working you may be on an older version of the theme, watch out for the latest version here : https://betterdiscord.app/theme/Comfy
