### ISSUE TITLE
Discolored/Default Parts

### ISSUE THREAD

**Issue by XxFabxX** [NYRI4/Comfy#44]
Friends part of the theme is discolored/default, Buttons as well, Bot buttons, etc
![image](https://user-images.githubusercontent.com/49923548/148656926-2e4d7531-301e-41c1-8077-b00b8e95bd76.png)
![image](https://user-images.githubusercontent.com/49923548/148656933-198ab53c-08b1-471f-80fa-191fe9663670.png)
![image](https://user-images.githubusercontent.com/49923548/148656939-87e75016-4d9c-4f8c-a249-5c1a3ac951df.png)

**Comment by Ushie** [comment]
Discord changed the class names for many things, Nyria is already aware of the issue, it'll take some time

**Comment by XxFabxX** [comment]
> Discord changed the class names for many things, Nyria is already aware of the issue, it'll take some time

ooh sorry, i didnt see any message on the discord about it so i was confused
