### ISSUE TITLE
Server Talk Notification/Pings On The Server List Broken

### ISSUE THREAD

**Issue by XxFabxX** [NYRI4/Comfy#45]
Hi! Notifications(chat)/pings on servers are broken, they dont show up on the server list, if u click on the server, it shows up above the white bar weirdly, Hope this isnt from me (i disabled all plugins and its still the same)
![image](https://user-images.githubusercontent.com/49923548/148769963-6fc31402-76e7-4848-8127-12226eca40ed.png)
![image](https://user-images.githubusercontent.com/49923548/148769970-e98fd7dd-0b59-4132-aee5-a550cfb9a7a3.png)

**Comment by XxFabxX** [comment]
> I don't know CSS almost at all and I never changed the discord CSS but I come up with this code (It was mostly trial and error)
> 
> ```
> .listItem-3SmSlK .pill-2RsI5Q.wrapper-z5ab_q::before { left: 6px !important;}
> .pill-2RsI5Q { z-index: 1 !important;}
> .wrapper-z5ab_q {overflow: unset;}
> .unread .pill-2RsI5Q.wrapper-z5ab_q { display:flex !important; }
> ```
> 
> First line changes server icons inside folders so they match the rest. About the rest well it works sort of, I cannot get rid of the white dot on left, I hope it doesn't break anything else.
> 
> You can put this in Settings > PowerCord > Themes > QuickCSS for now.
> 
> ![image](https://user-images.githubusercontent.com/11234896/148791780-0158f0fd-1403-49a9-8268-8ce3b0b6364f.png)

sorry i forgot to reply, that works great for now! thanks

**Comment by TheMongoloid** [comment]
Use this: [https://laynetheepic.github.io/projects/pc-theme-converter/](url)

**Comment by NYRI4** [comment]
A fix as been made, thanks for the support.
