### ISSUE TITLE
Gap in thread channel names

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [NYRI4/Comfy#47]
There seems to be a gap in the thread channel names ~~due to higher resolutions~~ when the scrollbars are removed? Unsure if its intended but it looks out of place
![image](https://user-images.githubusercontent.com/62061444/149201346-565d42a1-fa29-46e6-9f2f-d2a6b5f8a513.png)
Without any theme:
![image](https://user-images.githubusercontent.com/62061444/149201427-ee9139be-c73d-4523-b3fb-438844781316.png)
And i have not modified the theme at all other than changing colors to suit my liking.

**Comment by NYRI4** [comment]
What do you mean by higher resolution ? Screen resolution ? Different zoom scale on Discord ? I tried both but everything got fine

**Comment by TranquillyUnpleasant** [comment]
Ok this seems to be caused specifically when you comment out the code that removes scrollbars
![image](https://user-images.githubusercontent.com/62061444/149424628-4d01f437-13f0-4f86-8131-e0ed2bdb02f1.png)
