### ISSUE TITLE
Custom status colors not working

### ISSUE THREAD

**Issue by JustDownloadin** [NYRI4/Comfy#50]
For some reason, changing status colors to anything other than default does nothing, they remain default. All other color changes seem to work fine. Any idea on how to fix this? (Changed status colors to other random ones for this example)

![imagen](https://user-images.githubusercontent.com/83708957/149601872-959f3b07-5ffa-481a-9d4e-cf5276837764.png)

**Comment by NYRI4** [comment]
Fixed - https://github.com/NYRI4/Comfy/commit/54838c6482b10503b9f979f4dac3af85ae608a21. Thanks for reporting this issue.
