### ISSUE TITLE
Status Picker Menu is kinda screwed.

### ISSUE THREAD

**Issue by salocinyeet** [NYRI4/Comfy#52]
When I try to change my status, the menu is broken, what it does it brings up half but no option to change my status and your profile from the server/DM you are in.
![image](https://user-images.githubusercontent.com/32781165/150883971-d6960adb-bc45-4403-895b-33797bab1f12.png)

**Comment by MichaelDavidGK** [comment]
Couldn't reproduce the error

**Comment by salocinyeet** [comment]
Oh there was a plugin (Permission Viewer and something else) that was interfering with the status picker. I have since disabled it .
