### ISSUE TITLE
Statuses are all shown as online

### ISSUE THREAD

**Issue by LunarRuby** [NYRI4/Comfy#55]
Status for every user in the user list and the member list are all shown as online, when looking at a user's status in their dms at the top by their name, it is accurate to what it actually is.

**Comment by MichaelDavidGK** [comment]
![image](https://user-images.githubusercontent.com/39009683/152423040-6b9999f9-c609-4677-8dc1-09f094405de2.png)
It's not theme that is bugged

**Comment by LunarRuby** [comment]
Do you have an idea that I might have that might be bugging it? A few examples would be appriciated!

**Comment by LunarRuby** [comment]
Found it, plugin called "color-sighted"
