### ISSUE TITLE
[BUG] Primary color isn't the new blurple, or isn't customizable

### ISSUE THREAD

**Issue by Juknum** [NYRI4/Comfy#57]
The primary color used everywhere still use the old blurple color: 
![image](https://user-images.githubusercontent.com/49886317/154867773-0b0e4a8e-2c15-4670-9948-68001acc7f81.png)
![image](https://user-images.githubusercontent.com/49886317/154867780-9b713efd-dc99-4c9e-a7db-eb487d38172a.png)
![image](https://user-images.githubusercontent.com/49886317/154867791-5ac6b372-f390-4faf-9a5a-81f8e2377a43.png)

I don't know if it's intended, but I didn't see any easy to use variables to modify it without modifying everything xd

new color: #5865F2
old: #7289DA

**Comment by NYRI4** [comment]
The primary color of Comfy is intended to be the old one of Discord since Discord isn't using it anymore, I'm taking it, for customization :
![DiscordCanary_OJk6a8vNhk](https://user-images.githubusercontent.com/65369563/154867913-24934c9e-632b-4671-9f3d-78ae486c9f83.png)

**Comment by Juknum** [comment]
Okay thanks!
(for those wondering, the variable name is `--background-accent`)
