### ISSUE TITLE
Multiple issues, will list down in the description

### ISSUE THREAD

**Issue by SetuCoder** [NYRI4/Comfy#6]
**Please note I'm currently running macOS 11.2.1 on a MacBook Air, using the theme with BandagedBetterDiscord**

- **Discord Online/Offline Status color ring or dot**
   
![Screenshot 2021-02-25 at 9 56 28 AM](https://user-images.githubusercontent.com/58362876/109102854-bc49b180-774f-11eb-8291-b46ff9bbcb0f.png) 
Please make sure the status is actually visible, it's a bit longer route to check in what status I'm currently in. I'm using RadialStatus v1.0.0 by Gibbu#1211, but even by disabling that, the status doesn't appear on the pfp. 

- **The Custom Status Placement**

![Screenshot 2021-02-25 at 10 01 35 AM](https://user-images.githubusercontent.com/58362876/109103330-b1dbe780-7750-11eb-869e-f3e5506a695b.png)
I like the idea of making the popup hovering, but a little touch-up would be nice. Place the custom status modifier above or below the online/offline modifiers and make sure that the text is visible.

- **User Popup menu is messy**

![Screenshot 2021-02-25 at 10 10 33 AM](https://user-images.githubusercontent.com/58362876/109104280-b5bc3980-7751-11eb-826f-23e0ad278e9f.png)
How can I describe this bruh? It's soo messed up. Please show up the pfp above the name, and reduce the size of the rich presence and make the button text visible. And also a lil suggestion. Make the part of the popup which shows both name and user tag a bit hovering. It doesn't quite fit into the design language you used earlier. 

- **Useless elements in other user's popups**
![Screenshot 2021-02-25 at 10 20 47 AM](https://user-images.githubusercontent.com/58362876/109105242-87d7f480-7753-11eb-9d92-7e90759217e6.png)
Why is this "firey" even exist in the popup? It doesn't look good. 

- **Align the traffic light icons to the discord icon please!**
![Screenshot 2021-02-25 at 10 27 25 AM](https://user-images.githubusercontent.com/58362876/109105621-501d7c80-7754-11eb-83d7-5f07687aa270.png)
The perfectionist inside me is freaking out lmao

- **And finally the wavy thing u mentioned in your readme. It looks gorgeous. It doesn't work for me**
![68747470733a2f2f692e6962622e636f2f70314a477943362f696d6167652e706e67](https://user-images.githubusercontent.com/58362876/109106197-4ea08400-7755-11eb-8e20-acaac88e3fb2.png)

Please respond to me about what can be fixed and what cannot.

**Comment by NYRI4** [comment]
Fixed.
