### ISSUE TITLE
adding roles popup gets behind the user popup

### ISSUE THREAD

**Issue by FusionEzz** [NYRI4/Comfy#7]
![image](https://user-images.githubusercontent.com/68380349/109290701-dce13c80-781f-11eb-86bb-326fe9a6a513.png)
ye so as you can see there the menu for adding roles gets behind the user popout after clicking the "+" button to add roles. This happens with any user popout, doesn't matter if it's on the member list or on chat.

**Comment by SetuCoder** [comment]
### Doesn't Happen to me tho

![Screenshot 2021-02-26 at 7 19 35 PM](https://user-images.githubusercontent.com/58362876/109308087-91eb1780-7867-11eb-9f5e-e718d4945a46.png)

**Comment by NYRI4** [comment]
Closing this issue as my theme doesn't modify it, seems to be a problem on your side, either look at theme/plugins that you installed/check your quick css
