### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by JeroenoBoy** [NYRI4/Comfy#8]
first: Add a way to see which discord server i've selected, or just add  ![image](https://user-images.githubusercontent.com/26047623/109843874-db62aa80-7c4b-11eb-89b6-d343dcc78828.png) back

second: add some kind of border or change the color of the roles menu so it doesn't blend in with the background so much
![image](https://user-images.githubusercontent.com/26047623/109844098-1664de00-7c4c-11eb-8cca-c26f5c04669f.png)

**Comment by NYRI4** [comment]
Fixed.
