### ISSUE TITLE
Unread Indicator is broken, as well as the ping indicator.

### ISSUE THREAD

**Issue by hanakomisa** [NYRI4/Comfy#9]
Right now the ping indicator is in the normal position instead of being on the left side of the icon like it was supposed to.

Also seems like all server unread indicators are broken, along with the current selected server (which was [reported here](https://github.com/NYRI4/Comfy/issues/8))
![image](https://user-images.githubusercontent.com/32932571/109909428-5eb0ea00-7ca6-11eb-9630-95cff922ec79.png)

**Comment by hanakomisa** [comment]
Current known workaround for the notification pills: (Thanks Rud#4634!)

`.pill-1m5BUr:not(.unread), .pill-1m5BUr:not([vz-unread]), 
.pill-31IEus:not(.unread), .pill-31IEus:not([vz-unread]) { display: flex;}`

Note, as snapper#0001 commented, if you're not using Vizality, you can use this instead:

`.pill-1m5BUr:not(.unread), 
.pill-31IEus:not(.unread) { display: flex;}`

**Comment by NYRI4** [comment]
I'm not supporting unread pills for BetterDiscord anymore because those don't have something to target them, this issue should be fixed on BetterDiscord now, having the basic unread pill.
